### PR TITLE
Apply kernel

### PR DESCRIPTION
**Pull request by VincentVerelst**
Added a first implementation of the apply_kernel process along with some tests.

### CODE REVIEW

**Comment by clausmichele** [comment]
Hi @VincentVerelst, I've tried the code with a practical example and it seems fine.

```python
from openeo.local import LocalConnection
local_conn = LocalConnection("./")

url = "https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a"
spatial_extent =  {"east": 11.40, "north": 46.52, "south": 46.46, "west": 11.25}
temporal_extent = ["2022-06-01", "2022-06-30"]
bands = ["red", "nir"]
properties = {"eo:cloud_cover": dict(lt=80)}
s2_datacube = local_conn.load_stac(
    url=url,
    spatial_extent=spatial_extent,
    temporal_extent=temporal_extent,
    bands=bands,
    properties=properties,
)

b04 = s2_datacube.band("red")
b08 = s2_datacube.band("nir")
ndvi = (b08 - b04) / (b08 + b04)
ndvi_median = ndvi.reduce_dimension(dimension="time", reducer="median")
result_ndvi = ndvi_median.execute()
result_ndvi.plot.imshow(vmin=0,vmax=1,cmap="Greens")
```

Untitled

```python
import numpy as np
ndvi_median_blur = ndvi_median.apply_kernel(kernel=np.ones((5,5)),factor=1/25)
ndvi_median_blur_xr = ndvi_median_blur.execute()
ndvi_median_blur_xr.plot.imshow(vmin=0,vmax=1,cmap="Greens")
```

Untitled-1

**Comment by soxofaan** [comment]
FYI @LukeWeidenwalker   we want to assign reviewers for this PR, but there is no option to do that in the right column:
image

**Comment by clausmichele** [comment]
I do see a list of people, not sure if I have different rights on this repo:
image

**Comment by m-mohr** [comment]
The spec says: "Each level of the kernel must have an uneven number of elements, otherwise the process throws a KernelDimensionsUneven exception.". If you don't throw an error the process spec for this implementation should explain what happens in this case.

**Comment by GeraldIr** [comment]
@VincentVerelst Can you confirm what happens in the case of an uneven kernel and if it is in line with the spec, if yes I will merge it, otherwise I would request a kernel dimension check and throwing the correct exception.

**Comment by VincentVerelst** [comment]
@GeraldIr , I still need to add the kernel dimension check, will keep you posted!

**Comment by VincentVerelst** [comment]
Added the KernelDimensionsUneven exception.

**Pull request merged**
